# Generated by Django 4.2 on 2025-02-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='organizer',
        ),
    ]
