# Generated by Django 4.2 on 2025-02-07 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_organization_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='competition',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
