# Generated by Django 4.2 on 2025-02-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_competition_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='platform',
            field=models.CharField(default='Virtual', max_length=100, verbose_name='Платформа'),
        ),
    ]
