# Generated by Django 4.2 on 2025-02-08 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_customuser_public_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bracket_type', models.CharField(choices=[('TOP_32', 'Top 32'), ('TOP_16', 'Top 16'), ('TOP_8', 'Top 8'), ('TOP_4', 'Semi-finals'), ('TOP_2', 'Finals')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_brackets', to='core.stage')),
            ],
            options={
                'unique_together': {('stage', 'bracket_type')},
            },
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_order', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('PENDING', 'Ожидает начала'), ('IN_PROGRESS', 'В процессе'), ('COMPLETED', 'Завершен'), ('CANCELLED', 'Отменен')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='core.battlebracket')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_follows', to=settings.AUTH_USER_MODEL)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_leads', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['battle_order'],
                'unique_together': {('bracket', 'battle_order')},
            },
        ),
        migrations.CreateModel(
            name='QualificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('score', models.DecimalField(decimal_places=1, max_digits=5)),
                ('angle_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('line_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('style_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('speed_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_results', to='core.stage')),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('stage', 'participant', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='BattleRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(choices=[('LEAD', 'Лидирующий заезд'), ('FOLLOW', 'Догоняющий заезд')], max_length=10)),
                ('angle_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('line_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('style_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('speed_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('deductions', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('total_score', models.DecimalField(decimal_places=1, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.battle')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('battle', 'run_type')},
            },
        ),
    ]
